#SPDX-License-Identifier: MIT-0
---
# tasks file for setup

- name: Update and Upgrade apt packages
  apt:
    update_cache: yes
    upgrade: dist

- name: Install python 3
  apt:
    name: python3
    state: present

- name: Install docker
  apt:
    name: docker.io
    state: present

- name: Install docker-compose
  apt:
    name: docker-compose
    state: present

